function cfgPartes = configurar_partes_estructurales_vtol()
%CONFIGURAR_PARTES_ESTRUCTURALES_VTOL Define partes estructurales a extraer.
%
% Sistema interno:
%   x = longitudinal desde nariz hacia cola [m]
%   y = lateral [m]
%
% Las regiones se definen en mm.

cfgPartes.usar = true;
cfgPartes.metodoDefault = "region";
cfgPartes.shrinkFactorBoundary = 0.85;

% Crear arreglo de estructuras con campos fijos
partes = crear_arreglo_partes_vacio();

% ============================================================
% PARTES ESTRUCTURALES
% x = longitudinal desde nariz hacia cola [mm]
% y = lateral [mm]
% ============================================================

partes = agregar_parte(partes, ...
    "Fuselaje", "estructura", "region", "", ...
    0, 990, -90, 90, ...
    0, NaN, "PLA/PETG", "Fuselaje principal impreso 3D");

partes = agregar_parte(partes, ...
    "Ala izquierda", "estructura", "region", "", ...
    250, 650, 80, 650, ...
    0, NaN, "", "Ala izquierda desde DXF");

partes = agregar_parte(partes, ...
    "Ala derecha", "estructura", "region", "", ...
    250, 650, -650, -80, ...
    0, NaN, "", "Ala derecha desde DXF");

partes = agregar_parte(partes, ...
    "Cola izquierda", "estructura", "region", "", ...
    700, 990, 40, 300, ...
    0, NaN, "", "Cola/V-tail izquierda");

partes = agregar_parte(partes, ...
    "Cola derecha", "estructura", "region", "", ...
    700, 990, -300, -40, ...
    0, NaN, "", "Cola/V-tail derecha");

partes = agregar_parte(partes, ...
    "Soporte motor izquierdo", "estructura", "region", "", ...
    100, 420, 220, 650, ...
    0, NaN, "", "Brazo o soporte del motor izquierdo");

partes = agregar_parte(partes, ...
    "Soporte motor derecho", "estructura", "region", "", ...
    100, 420, -650, -220, ...
    0, NaN, "", "Brazo o soporte del motor derecho");

partes = agregar_parte(partes, ...
    "Soporte motor trasero", "estructura", "region", "", ...
    650, 990, -120, 120, ...
    0, NaN, "", "Soporte del motor trasero");

cfgPartes.partes = partes;

end


%% ============================================================
function partes = crear_arreglo_partes_vacio()
%CREAR_ARREGLO_PARTES_VACIO Crea arreglo struct con campos fijos.

parteBase = struct( ...
    'nombre', "", ...
    'tipo', "", ...
    'metodo', "", ...
    'layer', "", ...
    'x_min_mm', NaN, ...
    'x_max_mm', NaN, ...
    'y_min_mm', NaN, ...
    'y_max_mm', NaN, ...
    'z_mm', NaN, ...
    'masa_g', NaN, ...
    'material', "", ...
    'notas', "");

partes = repmat(parteBase, 0, 1);

end


%% ============================================================
function partes = agregar_parte(partes, nombre, tipo, metodo, layer, ...
                                x_min_mm, x_max_mm, y_min_mm, y_max_mm, ...
                                z_mm, masa_g, material, notas)
%AGREGAR_PARTE Agrega una parte estructural al arreglo.

p = struct( ...
    'nombre', string(nombre), ...
    'tipo', string(tipo), ...
    'metodo', string(metodo), ...
    'layer', string(layer), ...
    'x_min_mm', x_min_mm, ...
    'x_max_mm', x_max_mm, ...
    'y_min_mm', y_min_mm, ...
    'y_max_mm', y_max_mm, ...
    'z_mm', z_mm, ...
    'masa_g', masa_g, ...
    'material', string(material), ...
    'notas', string(notas));

partes(end+1,1) = p;

end